CREATE TABLE DAQUERY_VERSION
(
	ID bigint NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1) PRIMARY KEY,
	BUILD_NUM int,
	PACKAGE_URL varchar(500),
	RELEASE_DATE timestamp,
	VERSION varchar(50),
	FORCE_UPDATE boolean
);

INSERT INTO DAQUERY_VERSION (BUILD_NUM, PACKAGE_URL, RELEASE_DATE, VERSION, FORCE_UPDATE) VALUES (1469, 'http://localhost:8080/daquery-central/daquery_updates/daquery_update.zip', '2018-09-01 00:00:00', '1.1.1', false);
