CREATE TABLE DAQUERY_VERSION
(
	ID bigint NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1) PRIMARY KEY,
	BUILD_NUM int,
	PACKAGE_URL varchar(500),
	RELEASE_DATE timestamp,
	VERSION varchar(50),
	FORCE_UPDATE boolean
);