CREATE TABLE SITE_CONNECTION
(
	ID bigint NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1) PRIMARY KEY,
	SITE_ID bigint,
	STATUS varchar(20),
	NETWORK_ID bigint,
	DIRECTION varchar(20)
);

DROP TABLE OUTGOING_QUERY_SITES;
DROP TABLE INCOMING_QUERY_SITES;

