CREATE INDEX REQUESTERID ON "APP"."DAQUERY_REQUEST"(REQUESTER_ID);
CREATE INDEX SENTTIMESTAMPINDEX ON "APP"."DAQUERY_REQUEST"(SENT_TIMESTAMP);
CREATE INDEX DAQUERYREQUESTINDEX ON "APP"."DAQUERY_REQUEST"
(
  DIRECTION,
  ARCHIVED
);
CREATE INDEX REQID ON "APP"."DAQUERY_RESPONSE"(REQID);
CREATE INDEX INQUIRYID ON "APP"."INQUIRY"(INQUIRY_ID);