CONTAINER_NAME="daquery-testsite"
docker stop $CONTAINER_NAME
docker pull cborromeo/daquery-baseline
docker rm $CONTAINER_NAME
TOMCAT_REDIRECT_PORT="4000"
TOMCAT_DEBUG_PORT="7272"
OJDBC_DIR="/home/devuser"
DAQUERY_WAR_DIR="/home/devuser/projects/daquery/ws/target"
CONTAINER_OJDBC_DIR="/localdata/jdbc_driver"
CONTAINER_DAQUERY_WAR_DIR="/localdata/daquery_war"
TOMCAT_HOME="/usr/local/tomcat"
DAQUERY_CENT_URL="10.0.2.15"
DAQUERY_HOME="/home/devuser/daquery_data"
CONTAINER_DAQUERY_HOME="/localdata/daquery_data"
docker run --name $CONTAINER_NAME -dt -v $OJDBC_DIR:$CONTAINER_OJDBC_DIR -v $DAQUERY_WAR_DIR:$CONTAINER_DAQUERY_WAR_DIR -v $DAQUERY_HOME:$CONTAINER_DAQUERY_HOME -p $TOMCAT_REDIRECT_PORT:8080 -p $TOMCAT_DEBUG_PORT:8000 -e OJDBC_DIR=$OJDBC_DIR -e DAQUERY_WAR_DIR=$DAQUERY_WAR_DIR -e TOMCAT_HOME=$TOMCAT_HOME -e CONTAINER_OJDBC_DIR=$CONTAINER_OJDBC_DIR -e CONTAINER_DAQUERY_WAR_DIR=$CONTAINER_DAQUERY_WAR_DIR -e DAQUERY_HOME=$CONTAINER_DAQUERY_HOME/daquery-$TOMCAT_REDIRECT_PORT -e DAQUERY_CENT_URL=$DAQUERY_CENT_URL cborromeo/daquery-baseline:latest

