ALTER TABLE DAQUERY_REQUEST ADD COLUMN REQUESTER_SITE_ID BIGINT;
ALTER TABLE DAQUERY_RESPONSE ADD COLUMN STATUS_MESSAGE VARCHAR(1024);
ALTER TABLE INQUIRY ADD COLUMN INQUIRY_NAME VARCHAR(50);
ALTER TABLE INQUIRY ADD COLUMN INQUIRY_DESCRIPTION VARCHAR(500);

ALTER TABLE NETWORK ADD COLUMN MAX_DATE_SHIFT INTEGER;
ALTER TABLE NETWORK ADD COLUMN MIN_DATE_SHIFT INTEGER;
ALTER TABLE NETWORK ADD COLUMN SHIFT_DATES BOOLEAN;
ALTER TABLE NETWORK ADD COLUMN SERIALIZE_PATIENT_ID BOOLEAN;
ALTER TABLE NETWORK ADD COLUMN OBFUSCATE_AGGREGATE_RESULTS BOOLEAN;
ALTER TABLE NETWORK ADD COLUMN AGGREGATE_OBFUSCATE_TYPE VARCHAR(20);
ALTER TABLE NETWORK ADD COLUMN AGGREGATE_OBFUSCATE_PERCENT REAL;
ALTER TABLE NETWORK ADD COLUMN AGGREGATE_OBFUSCATE_RANGE INTEGER;
ALTER TABLE NETWORK ADD COLUMN AGGREGATE_OBFUSCATE_THRESHOLD INTEGER;
